#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <color/color.h>
#include <image/image.h>
#include <io/image_io.h>

#include "config.h"

#if HAVE_LIBNETPBM 

#include <pam.h>

int image_save_ppm(image_t * img, char *filename) {

    int i,j ;
    FILE* fichier ;
    if ( img == NULL ) {
        fprintf(stderr,"image_save_ppm: cannot save NULL image \n");
        return -1 ;
    }
	if (img->colorspace != CYAN_COLORTYPE_RGB) {
		fprintf(stderr,
			"image_save_ppm : Only RGB images are supported \n");
		return -2;
	}
    if ((img->rows==0)||(img->cols==0)) {
        fprintf(stderr,"image_save_ppm: one of the dimension of the image is zero\n");
        return -3 ;
    }
    fichier = fopen( filename, "w") ;
    if ( fichier == NULL ) {
        fprintf(stderr, "image_save_ppm: cannot open file %s for writing \n", filename) ;
        return -4 ;
    }
    pnm_writepnminit( fichier, img->cols, img->rows, (xelval) 255, PPM_TYPE, 1 );  
    xel* pixel_row = ppm_allocrow( img->cols ) ;
    for (i=0; i<img->rows;i++) {
        for (j=0;j<img->cols;j++) {
            pixel_row[j].r = (int) (255.0 * img->pixels[i*img->cols+j].coords[0]) ;
            pixel_row[j].g = (int) (255.0 * img->pixels[i*img->cols+j].coords[1]) ;
            pixel_row[j].b = (int) (255.0 * img->pixels[i*img->cols+j].coords[2]) ;
        }
        pnm_writepnmrow( fichier, pixel_row, img->cols, (xelval) 255, PPM_TYPE, 1 );
    }
    fclose(fichier) ;
    return 0 ;
}

#else

int image_save_ppm(image_t * img, char *filename) {
	FILE *handle;
	int line_length;
	int pixel_length;
	char current_pixel[70];
	int i, j;
	if (img == (image_t *) NULL) {
		fprintf(stderr,
			"image_save_ppm : Cannot save NULL image\n");
		return -1;
	}
	if (img->colorspace != CYAN_COLORTYPE_RGB) {
		fprintf(stderr,
			"image_save_ppm : Only RGB images are supported \n");
		return -2;
	}
	if ((img->rows == 0) || (img->cols == 0)) {
		fprintf(stderr,
			"image_save_ppm : image has a dimension of zero \n");
		return -3;
	}
	handle = fopen(filename, "w+");
	if (handle == (FILE *) NULL) {
		fprintf(stderr,
			"image_save_ppm : Could not open %s for writing\n",
			filename);
		return -4;
	}
	fprintf(handle, "P3\n");
	fprintf(handle, "# File generated by cyan version %d.%d \n",
		VERSION_MAJOR, VERSION_MINOR);
	fprintf(handle, "%d\n", img->cols);
	fprintf(handle, "%d\n", img->rows);
	fprintf(handle, "255 \n");
	for (j = 0; j < img->rows; j++) {
		line_length = 0;
		for (i = 0; i < img->cols; i++) {
			color_t color = img->pixels[j * img->cols + i];
			pixel_length =
			    sprintf(current_pixel, " %d %d %d",
				    (int) (color.coords[0] * 255),
				    (int) (color.coords[1] * 255),
				    (int) (color.coords[2] * 255));
			if (line_length + pixel_length > 70) {
				fprintf(handle, "\n");
				line_length = 0;
			}
			fprintf(handle, "%s", current_pixel);
			line_length += pixel_length;
		}
		fprintf(handle, "\n");
	}
	fclose(handle);
	return 0;		// FIXME
}

#endif
